server: 
  port: 8003

mybatis: 
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations: 
    - "classpath:mybatis/mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: com.chinasoft.springcloud_2.entity            # 别名类所在包


spring: 
  application: 
    name: SpringCloud-ORM                          #微服务的名字
  datasource: 
    driver-class-name: org.gjt.mm.mysql.Driver                # mysql驱动包      
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: "jdbc:mysql://localhost:3306/test"                    # 数据库名称
    username: root
    password: 123456
    dbcp2: 
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 2000                                    # 等待连接获取的最大超时时间
      min-idle: 5                                             # 数据库连接池的最小维持连接数
  cloud:
    loadbalancer:
      retry:
        enabled:true 
 
 #当前线程 启动之后 自动访问路径 去指定的注册中心URL中 注入服务中心
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
  instance: 
    instance-id: ORM数据持久微服务,端口号:8003       #自定义服务名称注册说明信息
    prefer-ip-address: true                                   #访问路径可以显示  开放IP地址
    

info: 
  app.name: SpringCloud-ORM:8002
  company.name: www.lzj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
 
 
       
ribbon:
  ReadTimeout:60000
  ConnectTimeout:60000      
         
  